services:

  auth:
    hostname: ${AUTH_HOST}
    build: .
    depends_on:
      - auth-db
    ports:
      - "5000:5000"
    env_file: ../../.env
    environment:
      - ENV=test
    secrets:
      - source: auth-cert
        target: cert
      - source: auth-key
        target: key
      - jwt-public-key
      - jwt-private-key
      - mongo-root-password

  auth-db:
    hostname: ${AUTH_DB_HOST}
    image: mongo:latest
    ports:
      - '27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo-root-password
      MONGO_INITDB_DATABASE: admin
    command: mongod --auth --quiet --logpath /dev/null
      --tlsAllowConnectionsWithoutCertificates
      --tlsMode preferTLS
      --tlsCertificateKeyFile /run/secrets/cert
      --tlsCAFile /run/secrets/cert
    secrets:
      - source: auth-mongo-fullchain
        target: cert
      - mongo-root-password


secrets:
  auth-cert:
    file: ../../certs/auth-cert.pem
  auth-key:
    file: ../../certs/auth-key.pem
  auth-mongo-fullchain:
    file: ../../certs/auth-mongo-fullchain.pem
  mongo-root-password:
    file: ../../secrets/mongo-root-password.txt
  jwt-public-key:
    file: ../../secrets/jwt-public-key.pub
  jwt-private-key:
    file: ../../secrets/jwt-private-key.pem