services:
   
  player:
    hostname: ${PLAYER_HOST}
    build: ./services/Player
    depends_on:
      player-db:
        condition: service_healthy
    # TODO: Remove exposed port, only for testing purposes
    ports:
      - "5000:5000"
    env_file: .env
    secrets:
      - cert
      - key

  player-db:
    image: mysql:5.7
    hostname: ${PLAYER_DB_HOST}
    env_file: .env
    restart: always
    ports:
      - "3306"
    volumes:
      - ase-player-db:/var/lib/mysql
      - .docker/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    secrets:
      - source: cert
      - source: key
    healthcheck:
      test: mysql -h localhost -u root -p$MYSQL_ROOT_PASSWORD -e "USE ${MYSQL_DB}"
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 10s
    # TODO: Add --ssl-cert=${CERT_PATH} --ssl-key=${KEY_PATH} --require_secure_transport=ON for HTTPS
    command: >
      mysqld
      --log-error-verbosity=1

  auction:
    hostname: ${AUCTION_HOST}
    build: ./services/Auction
    depends_on:
      auction-db:
        condition: service_healthy
    ports:
      - "5001:5000"
    env_file: .env
    secrets:
      - cert
      - key
    
  auction-db:
    image: mysql:5.7
    hostname: ${AUCTION_DB_HOST}
    env_file: .env
    restart: always
    ports:
      - "3306"
    volumes:
      - ase-auction-db:/var/lib/mysql
      - .docker/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    secrets:
      - source: cert
      - source: key
    healthcheck:
      test: mysql -h localhost -u root -p$MYSQL_ROOT_PASSWORD -e "USE ${MYSQL_DB}"
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 10s
    command: >
      mysqld
      --log-error-verbosity=1

  api-gateway:
    hostname: ${API_GATEWAY_HOST}
    build: ./services/Gateway
    depends_on:
      - player
      - auction
    ports:
      - "5002:5000"
    env_file: .env
    secrets:
      - cert
      - key
    healthcheck:
      test: curl -f https://${PLAYER_HOST}:5000 && curl -f https://${AUCTION_HOST}:5000
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 10s

secrets:
  cert:
    file: ./certs/cert.pem
  key:
    file: ./certs/key.pem

volumes:
  ase-player-db:
  ase-auction-db: