name: Integration Test

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/main.yml'
      - 'tests/**'
      - 'services/**'
      - 'docker-compose.yml'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Init repository
        run: chmod +x init.sh && ./init.sh

      - name: Rename .env.example
        run: mv .env.example .env
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Newman
        run: npm install -g newman
        
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Run Auth tests
        run: cd tests/integration && \
              chmod +x auth_test.sh && \
              ./auth_test.sh && \
              cd -

      - name: Run Player tests
        run: cd tests/integration && \
              chmod +x player_test.sh && \
              ./player_test.sh && \
              cd -